#declarar como se va a iniciar el servidor

services: #construir servicio
  webserver: #nombre del servicio
    build: #construir
      context: . #contexto, la carpeta en la que está ubicado
      dockerfile: Dockerfile #buscar el archivo Dockerfile para construir el contenedor
    volumes:
      - .:/app #de aquí se sincronizan los cambios en los archivos
    ports:
      - '80:80'